name: Extract, Processed, Modeling_data, Load

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    env:
      API_KEY_WAPI: ${{ secrets.API_KEY_WAPI }}
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'  

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Ejecutar script de extracción
        run: python extract.py

      - name: Subir datos extraídos
        uses: actions/upload-artifact@v2
        with:
          name: raw_data
          path: raw/*.json  # Asegurar que se suban todos los archivos JSON

