name: Extract, Processed, Modeling_data, Load

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    env:
      API_KEY_WAPI: ${{ secrets.API_KEY_WAPI }}
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Ejecutar script de extracción
        run: python extract.py

      - name: Subir datos extraídos
        uses: actions/upload-artifact@v4
        with:
          name: raw_data
          path: raw/*.json  

  processed:
    runs-on: ubuntu-latest
    needs: extract
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Descargar datos extraídos
        uses: actions/download-artifact@v4
        with:
          name: raw_data
          path: raw

      - name: Ejecutar script de procesamiento
        run: python processed.py

      - name: Subir datos procesados
        uses: actions/upload-artifact@v4
        with:
          name: processed_data
          path: processed/*.csv

  modeling_data:
    runs-on: ubuntu-latest
    needs: processed
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Descargar datos procesados
        uses: actions/download-artifact@v4
        with:
          name: processed_data
          path: processed

      - name: Ejecutar script de modelado de datos
        run: python modelo_datos.py

      - name: Subir datos modelados
        uses: actions/upload-artifact@v4
        with:
          name: modeled_data
          path: modelo_datos/*.csv

  load:
    runs-on: ubuntu-latest
    needs: modeling_data
    env:
      USER: ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      HOST: ${{ secrets.HOST }}
      PORT: ${{ secrets.PORT }}
      DATABASE: ${{ secrets.DATABASE }}
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Descargar datos modelados
        uses: actions/download-artifact@v4
        with:
          name: modeled_data
          path: modelo_datos

      - name: Ejecutar script de carga de datos
        run: python load.py
